[tox]
envlist = py36

[testenv:py36]
commands =
    flake8 itemscoringpathogen
    pytest itemscoringpathogen
deps =
    pytest
    wemake-python-styleguide
    pytest-flake8
    pytest-cov
    flake8
    flake8-mypy
whitelist_externals = python

[bdist_wheel]
universal = 1


[coverage:run]
branch = True


[flake8]
no-accept-encodings = True
max-complexity = 6
statistics = False
max-line-length = 100
doctests = False
enable-extensions = G
isort-show-traceback = True
inline-quotes = double

# Exclude some pydoctest checks globally:
ignore =
    D100, D104, D401, Z305, T484

per-file-ignores =
  horsekickerpy/tests/*.py: S101, S404, S603, S607, Z211, D103, Z202


[pytest]
# py.test options:
norecursedirs = tests/fixtures *.egg .eggs dist build docs .tox .git __pycache__

filterwarnings =
  ignore::DeprecationWarning
  ignore::PendingDeprecationWarning
  ignore::FutureWarning

# You will need to measure your tests speed with `-n auto` and without it,
# so you can see whether it gives you any performance gain, or just gives
# you an overhead. See `docs/template/development-process.rst`.
addopts =
  --strict
  --cov=horsekickerpy
  --cov-report=term-missing:skip-covered
  --cov-report=html
  --cov-fail-under=90


[isort]
# See https://github.com/timothycrosley/isort#multi-line-output-modes
multi_line_output = 3
include_trailing_comma = true
default_section = FIRSTPARTY
line_length = 99


[mypy]
# The mypy configurations: http://bit.ly/2zEl9WI
python_version = 3.6

check_untyped_defs = True
disallow_any_explicit = True
disallow_any_generics = True
disallow_untyped_calls = True
ignore_errors = False
ignore_missing_imports = True
strict_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True


[doc8]
ignore-path = docs/_build
max-line-length = 100
sphinx = True
